# Required connection configs for Kafka producer, consumer, and admin
bootstrap.servers=pkc-p11xm.us-east-1.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=WUUQXTMIYMO3SKJB
sasl.password=KST8V2tb2IwDJSYxRZw6w0ALFMJMApxJAlHe+DsxqAZy6QyXpspFnq6EykuzZxaB

# Best practice for higher availability in librdkafka clients prior to 1.7
session.timeout.ms=45000

client.id=ccloud-nodejs-client-563cba63-3b04-4735-925b-124e5a2cb7b2